"""Small Blender front end for the shared ONUA3D container/identity core.

The distributable is generated by tools/build_blender_onua3d.py from these
same sources. Blender never calls a native UA writer.
"""
import hashlib
import io
from pathlib import Path
import tempfile

import bpy
from bpy.props import PointerProperty, StringProperty
from bpy_extras.io_utils import ExportHelper, ImportHelper

from onua3d_package import read_onua3d, repack_onua3d, Onua3dImportError

bl_info = {
    'name': 'OpenNeoUA 3D', 'author': 'OpenNeoUA Studio', 'version': (1, 0, 0),
    'blender': (4, 5, 0), 'location': 'File > Import / Export',
    'description': 'Position-only ONUA3D interchange with OpenNeoUA Studio',
    'category': 'Import-Export',
}


class ONUA3DSource(bpy.types.PropertyGroup):
    filepath: StringProperty(name='Source ONUA3D', subtype='FILE_PATH')
    sha256: StringProperty(name='Source SHA-256')


def open_onua3d(context, filepath):
    """Validate first, then open in a NEW scene without clearing existing work."""
    source = Path(filepath).resolve()
    data = source.read_bytes()
    _, members = read_onua3d(io.BytesIO(data))
    previous_scene = context.window.scene
    scene = bpy.data.scenes.new(source.stem)
    before_objects = set(bpy.data.objects)
    try:
        context.window.scene = scene
        with tempfile.TemporaryDirectory(prefix='OpenNeoUA_blender_') as temporary:
            glb = Path(temporary) / 'scene.glb'
            glb.write_bytes(members['scene.glb'])
            if bpy.ops.import_scene.gltf(filepath=str(glb), merge_vertices=False) != {'FINISHED'}:
                raise Onua3dImportError('Blender could not import scene.glb')
        scene.onua3d_source.filepath = str(source)
        scene.onua3d_source.sha256 = hashlib.sha256(data).hexdigest()
        return scene
    except Exception:
        context.window.scene = previous_scene
        for obj in set(bpy.data.objects) - before_objects:
            bpy.data.objects.remove(obj, do_unlink=True)
        bpy.data.scenes.remove(scene)
        raise


def export_onua3d(context, filepath):
    """Export the current scene with the validated glTF profile, then repack."""
    source = context.scene.onua3d_source
    if not source.filepath or not source.sha256:
        raise Onua3dImportError('No source ONUA3D association: use File > Import > OpenNeoUA 3D first')
    path = Path(source.filepath)
    if not path.is_file():
        raise Onua3dImportError('Source ONUA3D package is missing; open it again')
    if hashlib.sha256(path.read_bytes()).hexdigest() != source.sha256:
        raise Onua3dImportError('Source ONUA3D package changed; open it again')
    # Validate before invoking Blender's exporter or creating destination files.
    read_onua3d(path)
    with tempfile.TemporaryDirectory(prefix='OpenNeoUA_blender_export_') as temporary:
        glb = Path(temporary) / 'scene.glb'
        result = bpy.ops.export_scene.gltf(
            filepath=str(glb), export_format='GLB', export_attributes=True,
            export_extras=True, export_normals=True, use_active_scene=True,
            export_apply=False, export_animations=True, export_current_frame=False)
        if result != {'FINISHED'}:
            raise Onua3dImportError('Blender could not export scene.glb')
        return repack_onua3d(path, glb.read_bytes(), filepath, source_sha256=source.sha256)


class IMPORT_SCENE_OT_onua3d(bpy.types.Operator, ImportHelper):
    bl_idname = 'import_scene.onua3d'
    bl_label = 'Open OpenNeoUA 3D'
    filename_ext = '.onua3d'
    filter_glob: StringProperty(default='*.onua3d', options={'HIDDEN'})

    def execute(self, context):
        try:
            open_onua3d(context, self.filepath)
        except (RuntimeError, OSError, ValueError) as exc:
            self.report({'ERROR'}, str(exc))
            return {'CANCELLED'}
        self.report({'INFO'}, 'Opened ONUA3D in a new scene. Edit vertex positions only.')
        return {'FINISHED'}


class EXPORT_SCENE_OT_onua3d(bpy.types.Operator, ExportHelper):
    bl_idname = 'export_scene.onua3d'
    bl_label = 'Export OpenNeoUA 3D'
    filename_ext = '.onua3d'
    filter_glob: StringProperty(default='*.onua3d', options={'HIDDEN'})

    def execute(self, context):
        try:
            export_onua3d(context, self.filepath)
        except (RuntimeError, OSError, ValueError) as exc:
            self.report({'ERROR'}, str(exc))
            return {'CANCELLED'}
        self.report({'INFO'}, 'Exported a new ONUA3D; the original native family is preserved.')
        return {'FINISHED'}


def _import_menu(self, context):
    self.layout.operator(IMPORT_SCENE_OT_onua3d.bl_idname, text='Open OpenNeoUA 3D')


def _export_menu(self, context):
    self.layout.operator(EXPORT_SCENE_OT_onua3d.bl_idname, text='Export OpenNeoUA 3D')


_CLASSES = (ONUA3DSource, IMPORT_SCENE_OT_onua3d, EXPORT_SCENE_OT_onua3d)


def register():
    for cls in _CLASSES: bpy.utils.register_class(cls)
    bpy.types.Scene.onua3d_source = PointerProperty(type=ONUA3DSource)
    bpy.types.TOPBAR_MT_file_import.append(_import_menu)
    bpy.types.TOPBAR_MT_file_export.append(_export_menu)


def unregister():
    bpy.types.TOPBAR_MT_file_export.remove(_export_menu)
    bpy.types.TOPBAR_MT_file_import.remove(_import_menu)
    del bpy.types.Scene.onua3d_source
    for cls in reversed(_CLASSES): bpy.utils.unregister_class(cls)
